### PR TITLE
Stop using the DocumentAndElementEventHandlers interface mixin

### PR DESCRIPTION
**Pull request by foolip**
This mixin will be removed from HTML, and the 3 event handler attributes
will be added to GlobalEventHandlers instead:
https://github.com/whatwg/html/pull/8096
https://github.com/web-platform-tests/wpt/pull/36398

### CODE REVIEW

**Comment by bkardell** [comment]
Thanks @foolip ... Makes sense to me

**Comment by foolip** [comment]
@bkardell can you review this? It would be good to have this reviewed and then merged around the same time as https://github.com/whatwg/html/pull/8096.

**Review by bkardell — APPROVED** [review]

**Comment by bkardell** [comment]
We can happily accept this when it's ready to merge in HTML

**Comment by foolip** [comment]
@bkardell https://github.com/whatwg/html/pull/8096 has now been merged, can you merge this PR? Thanks!

**Comment by fred-wang** [comment]
@foolip Done. Thanks for this submitting this PR.

**Pull request merged**
