### PR TITLE
regenerate using operator-dictionary.py

### PR DESCRIPTION
**Pull request by davidcarlisle**
As discussed in email, this regenerates the html tables from unicode.xml, If any of these changes are not wanted  we should revert the relevant entries in unicode.xml, to get a stable base going forward, to allow extra data to be added to the sources (eg as happens every Unicode release)  while checking that no changes have been made to normative data in the relevant specifications.

### CODE REVIEW

**Comment by fred-wang** [comment]
Yes, my preference is that we revert all the changes to unicode.xml that affect the current MathML core spec.

**Comment by davidcarlisle** [comment]
@fred-wang  Some of the changes are clearly correct notably  Unicode TR and TeX define characters to be relations, forcing an incompatible interpretation here will just standardise confusion forever.  The baseline for the First Public Working draft shoudl be as accurate as we can reasonably make it.

**Comment by NSoiffer** [comment]
We did a bunch of work to align characters with TeX (mostly more obscure characters, but still). Also, with a list that big, bugs clearly will be there. Deyan found one where "%" did not have a postfix entry, meaning that the spacing for "%" will be wrong. Bugs need to be fixed, so I don't think freezing the core spec is reasonable, and the master list clearly should be the xml-entities list.

**Comment by davidcarlisle** [comment]
@fred-wang the one change that adversely affected the mathml-core spec (issue #96) was fixed in xml-entities. I think it's important to use the same source file for all the specifications,  do you agree to this being merged now that #96 is fixed, before any FPWD ?

**Comment by fred-wang** [comment]
@davidcarlisle OK thanks. I haven't checked in details. I'm ok to merge this in MathML Core if that makes managing the spec easier in the short term, but I would wait before porting the changes to web-platform-tests so that it does not disturb current work in WebKit by Apple and in Chromium by Igalia. And also so that one does not need to regenerate big test fonts until we are sure the op dict is stable.

I also still disagree the op dictionary is supposed to be permanently unstable. I imagine that at some point, updates will not be that frequent and only be done for new operators introduced in future versions of Unicode. If there are still mistakes in existing characters, I believe they should be fixed before we launch the next update in wpt/browsers. But I don't think such an update is urgent right now.

**Comment by davidcarlisle** [comment]
@fred-wang  thanks.  If we sync things now it will be much easier going forward to check if any change  to unicode.xml  changes the core operator dictionary as any change will show up as a diff in the tables here. Currently that's harder as there are "existing legacy differences" you need to factor out. So I think this will work well for your stated aim of keeping the core opdict very stable. (This is not so different from the policy that has been in place for years now of not accepting any change to unicode.xml that would change the entity list for html5, as changing that would be ... unpopular...

**Comment by davidcarlisle** [comment]
following this merge I have reset https://w3c.github.io/mathml-core/ to build from the main branch

**Pull request merged**
